name: Manual
on:
  workflow_dispatch:
    inputs:
        greeting:
            type: string
            default: 'Hello'
            required: true
            description: 'The greeting to display'
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Run
          run: echo ${{ github.event.inputs.greeting }}, world!